### ISSUE TITLE
[BUG] Crash after update installs

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#156]
Kodi crashes everytime after installing an AH2 update. 

This issue happens on macOS, Windows 11, and Nvidia shield. I have noticed this over the past few days.

macOS: will crash when I click on the tv shows icon. 

https://user-images.githubusercontent.com/2873112/173256323-d5004a34-a3dd-4cbf-b12c-0a2f39a7d14c.mov

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8886921/kodi.log)

[kodi.old.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8886922/kodi.old.log)

Thanks

**Comment by Goldenfreddy0703** [comment]
Hey by anychance, has this happened to other skins when installing a new version of that skin?

**Comment by Blurayx** [comment]
> Hey by anychance, has this happened to other skins when installing a new version of that skin? Usually a workaround  is uninstalling the previous skin and then installing the new updated version of the skin. 

Never had this issue before with other skins.

**Comment by Goldenfreddy0703** [comment]
Oh then it's probably due to the Mac version of kodi. On Linux or Windows, I can update the skin fine using opendev tools or jurialmunkey's repo. Usually I just uninstall it then install a new version then switch back.

**Comment by chcore** [comment]
I am using Archlinux and I am now experiencing this, I think after trying to change the view type for TV Shows.

I tried removing the json file in the "script.skinvariables" directory (where I thought the view types might be stored), but that didn't fix it.

**Comment by Blurayx** [comment]
> I am using Archlinux and I am now experiencing this, I think after trying to change the view type for TV Shows.
> 
> I tried removing the json file in the "script.skinvariables" directory (where I thought the view types might be stored), but that didn't fix it. I have also tried removing settings.xml in the "skin.arctic.horizon.2" folder.
> 
> There doesn't seem to be anything in the crash log.
[
](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/187)

**Comment by chcore** [comment]
Got it working again by deleting the "script-skinviewtypes-checksum" and "script-skinviewtypes-hash" lines from the skin's settings.xml file in addon_data, and also deleting the "script.skinvariables" folder in addon_data. Hope this helps @jurialmunkey track it down.

**Comment by jurialmunkey** [comment]
Fixed in b768e17352bcd8cf2aedca3c11e0596a7913c246

**Comment by chcore** [comment]
Unfortunately the crashing has become worse since I updated today. Now it crashes in a loop right before loading the home screen (this is even after deleting the skin's settings in the addon_data folder, along with skin variables/shortcuts settings).

Even if I make it to the screen, If it try to configure the skin it causes an instant crash. Same thing happens if I try to access the "system info" section in the settings menu (the one with the "CPU" icon). I've scanned the crash logs and there's really nothing of use in there that I can see.

**Comment by Goldenfreddy0703** [comment]
Hey @chcore , I've had a few crashes on this skin when starting up kodi sometimes. Have you tried different skins in the past and have they crashed for you when using Arch?

**Comment by jurialmunkey** [comment]
@chcore what do you mean by "crashing in a loop"? 

The fact that you say you need to delete skinvariables settings points to a far larger issue that is unrelated to the crash that Blurayx was experiencing. 

A debug log would be good even if you don't think it is valuable.

**Comment by Goldenfreddy0703** [comment]
> The fact that you say you need to delete skinvariables settings points to a far larger issue that is unrelated to the crash that Blurayx was experiencing.

I'm just gonna say it, I think this could have something to do with Linux, he mentioned that he was using Arch Linux and using a specific version of python, me and a couple of developers were actually talking about a few kodi bugs happening with linux and this could relate to the crashing bug he is experiencing. Devs found a solution and it was to switch to the flapjack version of kodi to prevent the crashing. 

It could be that or it could be permissions and database stuff from looking at his log from the mac cause it did mention dataabse stuff and there were a few missing file locations that could not be accessed from what i could see.

**Comment by jurialmunkey** [comment]
Without a log it is all speculation. 

The bug Blurayx was experiencing is because when you update, the skinviewtypes includes file hasn't been built by skinvariables yet (originally the build trigger was only on the staratup screen). Kodi will crash if an include has an empty condition (condition must be boolean true/false not empty string).

The solution was to provide default false values and move the build trigger to home screen onload -- i.e. all viewtypes off by default until skinviewtypes builds, which happens when the home screen reloads after updating (skinvariables writes a checksum to avoid unnecessary rebuilding).

That chcore now experiences a crash going home indicates an issue with skinvariables. Since chcore can get it to work by deleting the addon_data folder for skinvariables, my guess is there is either some write or read permission problem in that folder because skin variables will write the config as a json dump on build (and load it to compare against the checksum when build triggered)

**Comment by chcore** [comment]
@jurialmunkey I have a systemd service that automatically re-launches kodi if/when it crashes. With this update it tends to crash during the loading screen, restart, crash during the loading screen again, etc.

I had been using a mod of Arctic Zephyr for many months without a crash (or at least none that I can remember). There are no crashes with Estuary either.

I've attached a debug log that just has me attempting to activate the "Configure skin..." menu option before it crashes.

[kodi_crashlog-20220715_233639.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9121294/kodi_crashlog-20220715_233639.log)

**Comment by chcore** [comment]
Here's another log with me attempting to access the part of the settings men with the CPU icon, which reliably triggers a crash.

[kodi_crashlog-20220715_234742.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9121339/kodi_crashlog-20220715_234742.log)

**Comment by jurialmunkey** [comment]
Can we just stick to looking at the crash on the home screen first. No idea why it would crash on system info.

**Comment by chcore** [comment]
@jurialmunkey sure, here's a debug log of a crash on the home screen.

[kodi_crashlog-20220716_004641.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9121814/kodi_crashlog-20220716_004641.log)

**Comment by jurialmunkey** [comment]
> @jurialmunkey sure, here's a debug log of a crash on the home screen.
> 
> [kodi_crashlog-20220716_004641.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9121814/kodi_crashlog-20220716_004641.log)

Thanks. Hmm looks like skinvariables completes fine. However, skin*shortcuts* starts but never finishes.

Nothing conclusive in the logs but there are two common themes to the crashes: 

1. Python scripts like skinshortcuts, skinvariables, and texturemaker which read and write data to Kodi's addon_data folder;
2. Kodi's ReplaceWindow() function 

With (1) skinshortcuts is also triggered onunload from skinsettings (i.e. where "Configure skin..." takes you). So I wouldn't be surprised if there's either some read/write permissions issue with that folder or a Python 3.10 specific issue. I've constantly had issues with Py 3.10 in general (for other projects, not just Kodi) and always end up downgrading to latest stable 3.9 version to avoid the headaches.

With (2) we have a couple of scenarios where ReplaceWindow() is called on a window that was also previous replaced. 

- Startup.xml calls ReplaceWindow(1198) [init screen] which calls ReplaceWindow(Home) once done
- All the settings windows call ReplaceWindow(newsettingswindow) when switching - so that would happen when going to/from skinsettings or systeminfo or profile settings to one of the other settings windows.

It is very possible that (2) is the problem. I can make a test case to rule it out. However, if it is the problem then that indicates a Kodi bug. There's not much that can be done from the skin side because the ReplaceWindow() builtin is the only way for a skin to rewrite window history for the back button to function correctly.

**Comment by chcore** [comment]
Thanks @jurialmunkey 

For (1) I tried a `chmod -R 777 ` on the kodi data folder, both before running kodi and while running kodi. I still See all three crashes. It would appear that a downgrade to python 3.9 would also require me to downgrade the kodi package on Arch Linux too, which I am a little hesitant to do (but may do for testing purposes)

I'm happy to test anything that would confirm or eliminate (2).

**Comment by jurialmunkey** [comment]
@chcore Can you try this version from the `test_for_repwin` branch. It swaps ReplaceWindow() for ActivateWindow() 
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/test_for_repwin.zip

You'll see why using ActivateWindow is a problem for the skin when you attempt back navigation but at least this will help rule out whether or not that's the problem. If it is the problem, I should be able to knock together a simple test case using Estuary to reproduce the bug and allow you to make a bug report on the Kodi github.

**Comment by jurialmunkey** [comment]
> Thanks @jurialmunkey
> 
> For (1) I tried a `chmod -R 777 ` on the kodi data folder, both before running kodi and while running kodi. I still See all three crashes. It would appear that a downgrade to python 3.9 would also require me to downgrade the kodi package on Arch Linux too, which I am a little hesitant to do (but may do for testing purposes)
> 
> I'm happy to test anything that would confirm or eliminate (2).

Yeah I'm leaning a bit more towards (2) anyway.

I think downgrading Python is going to be a headache in itself on Arch. It's been a long time since I used Arch but the focus has always been on latest everything so it is a bit of a pain downgrading. 

If there was something specific to Python I would expect at least some error message -- plus it doesn't really explain the SysInfo crash as I can see in your log you moved down rather than up (i.e. you didn't go via skinsettings at the top), so you wouldn't have passed through anything in the skin running a Python script.

**Comment by chcore** [comment]
No luck with the test_for_repwin.zip build I'm afraid. Am still able to trigger all three crashes. I've attached a debug log of the intermittent kodi startup crash, if it helps. Is there any component-specific logging I can enable that might help?

[kodi_crashlog-20220716_142000.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9125142/kodi_crashlog-20220716_142000.log)

**Comment by jurialmunkey** [comment]
Damn, I really thought that might be the cause.

Okay let's try turning off everything. Skinshortcuts / skinvariables etc.
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/test_for_repwin_v2.zip

Before installing, make a backup of your `script-skinshortcuts-includes.xml` and `script-skinviewtypes-includes.xml` from the skin 1080i folder because these won't be made and you'll need to drop these in manually.

**Comment by chcore** [comment]
With `tests_for_repwin_v2.zip` I no longer appear to get the startup crashes. Though they were intermittent, I just restarted kodi about 40 times and it was successful each time. The other two crashes (configuring skin settings, system info) still happen. I've attached a crash log for the former.

[kodi_crashlog-20220716_144857.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9125179/kodi_crashlog-20220716_144857.log)

**Comment by jurialmunkey** [comment]
Hmmm. I'm a bit stumped as to what the cause could be in the settings window then -- I'll need to think about it a bit more. I'm assuming it is two separate issues in that case and you're just unlucky because I haven't seen anyone else mention these specific issues.

I'd be interested to see at least if we can figure out what the Startup crash is caused by:

This version will disable skinshortcuts building on startup
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/test_disable_skinshortcuts.zip

And this version will disable skinvariables building on startup
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/test_disable_skinvars.zip

**Comment by alKODIque** [comment]
Hi there :)
I dont know if it's the same issue. But for me, Kodi crash everytime I update the skin AND when I open a menu. I meen, it doesnt crash automaticaly after the update. Just when I want to enter in a menu.
So I always need to restart Kodi after an update of the skin if I want to navigate and/or play something 
I'm on Nvidia shield Pro

Thanks :)

**Comment by Goldenfreddy0703** [comment]
Oh same too for some odd reason.

**Comment by alKODIque** [comment]
Lolll
I just update from 0.2.40 to 0.2.42.. and surprise!! No crash after the update..
It's probably just because I  decided to declare the issue lol

**Comment by Goldenfreddy0703** [comment]
> Lolll
> I just update from 0.2.40 to 0.2.42.. and surprise!! No crash after the update..
> It's probably just because I  decided to declare the issue lol

We're you able to access the rest of the menu or addons just fine?

**Comment by chcore** [comment]
> Hmmm. I'm a bit stumped as to what the cause could be in the settings window then -- I'll need to think about it a bit more. I'm assuming it is two separate issues in that case and you're just unlucky because I haven't seen anyone else mention these specific issues.
> 
> I'd be interested to see at least if we can figure out what the Startup crash is caused by:
> 
> This version will disable skinshortcuts building on startup https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/test_disable_skinshortcuts.zip
> 
> And this version will disable skinvariables building on startup https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/test_disable_skinvars.zip

Weirdly, I cannot reproduce the startup crash with either of those. Tried with and without the backed up `script-skinshortcuts-includes.xml` and `script-skinviewtypes-includes.xml`, and clearing out the addon_data for skinshortcuts and skinvariables in between.

Switched back to master and was able to reproduce the startup crash almost immediately.

**Comment by alKODIque** [comment]
@Goldenfreddy0703 
Everythings works just perfectly now.
I wish I declare the issue before, since it's the first time I dont have to restart Kodi after an update 😝

**Comment by Goldenfreddy0703** [comment]
Oh nice. Thank you

**Comment by jurialmunkey** [comment]
@alKODIque Yes, that was the issue I fixed in 9c93acc496e51d2ee5d73e318aa707eeab05f520 as described in this comment https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/156#issuecomment-1185560239 where the include conditions were empty because the user had not restarted Kodi after updating (and thus rebuilding the includes file). The solution was to provide a default false value and build includes on home.

The issue chcore is experiencing is different and based upon the latest info it appears to be due to both skinshortcuts and skinvariables running at the same time (not sure what the other crash is though).

**Comment by alKODIque** [comment]
Haa so this is not a Murphy Law! 
Thanks a lot for the explanation @jurialmunkey

**Comment by jurialmunkey** [comment]
@chcore - Could you try v1.0.4 of skinvariables. I've adjust where the reloadskin() condition occurs so that it happens after all files are written (previously it did a reloadskin immediately after writing the includes file and then wrote the new config if there were changes - I just had the thought that there's possibly a loop happening where it doesn't write the config in time).
https://github.com/jurialmunkey/script.skinvariables/archive/refs/tags/v1.0.4.zip

After installing v1.0.4 of skinvariables, then install latest version of AH2 (v0.2.43). I've moved out the skinvariable building to the MyNav windows so that it won't conflict with skinshortcuts. Thinking about the ReloadSkin() timing and how you said you only had the crash when both were enabled got me thinking that maybe both reloading at the same time is causing an issue.

Won't fix the issue in settings but I'm really hoping this will fix the startup/home crash. Then I can deal with the settings issue after.

**Comment by chcore** [comment]
> @chcore - Could you try v1.0.4 of skinvariables. https://github.com/jurialmunkey/script.skinvariables/archive/refs/tags/v1.0.4.zip
> 
> After installing v1.0.4 of skinvariables, then install latest version of AH2 (v0.2.43). https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/tags/v0.2.43.zip
> 
> In SV 1.0.4 I've adjusted the timing of the reloadskin() condition to happen after all files are written. Previously it was reloading immediately after the includes file was written and then writing the config settings in the background. Just had the thought that if for some reason the checksum doesn't save properly to the skin setting then it possibly gets stuck in a loop.
> 
> In AH2 0.2.43 I've moved the skinvariable build to the MyNav windows (and on Startup). That way it won't happen at the same time as SkinShortcuts (on Home). Thinking about the ReloadSkin() timing and how you said you only had the startup crash when both were enabled got me thinking that maybe both reloading at the same time is causing an issue.
> 
> I'm hoping these two adjustments are going to solve it so that only one script is ever reloading Kodi at any one time. It won't fix the issue in settings but I'm really hoping this will fix the startup/home crash. Then I can deal with the settings issue after.

Thanks, I think you've cracked it! I can no longer reproduce the startup crash. As expected, however, the other crashes still occur.

**Comment by jurialmunkey** [comment]
> Thanks, I think you've cracked it! I can no longer reproduce the startup crash.  ... I wonder why other people aren't experiencing these crashes, I don't think there's anything special about my setup

Excellent! 

I'm really not sure what the underlying issue is though. Two scripts doing ReloadSkin() while writing data shouldn't be a problem in most cases. I imagine there's just something to your particular hardware/software combo that doesn't like something specific Kodi is doing. 

All the crashes seem to be related to loading/reloading windows - could be something to do with window open/close animations in the skin, or how focus is being set onload etc. Really not sure though.

> As expected, however, the other crashes still occur.

It is just crashing in the settings screen now, correct?

**Comment by chcore** [comment]
> It is only crashing in the settings screen now, correct?

Yes, it crashes 100% of the time when I do any of these:

1. Attempt to configure the skin by activating "Configure skin..." in Look and Feel settings
2. Select the "CPU" icon in settings
3. Select the (bigger) "paint brush" icon in settings
4. Select the "photos" icon in settings

There could be others, I just haven't hunted for them.

**Comment by jurialmunkey** [comment]
> > It is only crashing in the settings screen now, correct?
> 
> Yes, it crashes 100% of the time when I do any of these:
> 
>     1. Attempt to configure the skin by activating "Configure skin..." in Look and Feel settings
> 
>     2. Select the "CPU" icon in settings
> 
>     3. Select the (bigger) "paint brush" icon in settings
> 
>     4. Select the "photos" icon in settings
> 
> 
> The other menu items do not appear to cause crashes. There could be things that do, I just haven't hunted for them.

Okay great, this is useful information. I think possibly the way the skin is switching the windows is a problem.

Could you try this `alternate_settings_switcher` version:
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/alternate_settings_switcher.zip

**Comment by chcore** [comment]
> Could you try this `alternate_settings_switcher` version: https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/alternate_settings_switcher.zip

Some progress with that version, (2) and (4) appear to be resolved. The other two remain!

**Comment by jurialmunkey** [comment]
> > Could you try this `alternate_settings_switcher` version: https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/alternate_settings_switcher.zip
> 
> Some progress with that version, (2) and (4) appear to be resolved. The other two remain!

Ah whoops, I left something in that I didn't mean to. Could you try this v2:
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/alternate_settings_switcher_v2.zip

**Comment by chcore** [comment]
> Ah whoops, I left something in that I didn't mean to. Could you try this v2: https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/alternate_settings_switcher_v2.zip

No luck I'm afraid, seems to behave the same as `alternate_settings_switcher` v1

**Comment by jurialmunkey** [comment]
Hmmm okay. try v3
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/alternate_settings_switcher_v3.zip

If this doesn't work, I'm out of ideas! (for now at least).

**Comment by chcore** [comment]
> Hmmm okay. try v3 https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/alternate_settings_switcher_v3.zip
> 
> If this doesn't work, I'm out of ideas! (for now at least).

No different than v2 unfortunately. I've attached a crash log of (3) if it's any help.

[kodi_crashlog-20220716_193340.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9125500/kodi_crashlog-20220716_193340.log)

**Comment by jurialmunkey** [comment]
I'm out of ideas. I'll have to think about it a bit more because that v3 pretty much eliminates what I _thought_ might be the issue

I'll merge these v3 changes into main anyway as it is a better approach to the switcher in general.

**Comment by chcore** [comment]
I have noticed that (1) and (3) have been fixed in v0.2.45, was this intentional? I can confirm those crashes occur in v0.2.44 100% of the time.

Not quite there yet though, I now get a crash when activating "Customise home menu" as in #344. I'll post my crash log there.
